<?php

/**
 * BaseDepartment
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property Doctrine_Collection $Roles
 * 
 * @method string              getName()  Returns the current record's "name" value
 * @method Doctrine_Collection getRoles() Returns the current record's "Roles" collection
 * @method Department          setName()  Sets the current record's "name" value
 * @method Department          setRoles() Sets the current record's "Roles" collection
 * 
 * @package    bristol-old-vic-archive
 * @subpackage model
 * @author     Steve Lacey
 * @version    SVN: $Id$
 */
abstract class BaseDepartment extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('department');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Role as Roles', array(
             'local' => 'id',
             'foreign' => 'department_id',
             'onDelete' => 'cascade',
             'cascade' => array(
             0 => 'delete',
             )));
    }
}