<?php

/**
 * BaseGenre
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property Doctrine_Collection $Productions
 * @property Doctrine_Collection $ProductionGenre
 * 
 * @method string              getName()            Returns the current record's "name" value
 * @method Doctrine_Collection getProductions()     Returns the current record's "Productions" collection
 * @method Doctrine_Collection getProductionGenre() Returns the current record's "ProductionGenre" collection
 * @method Genre               setName()            Sets the current record's "name" value
 * @method Genre               setProductions()     Sets the current record's "Productions" collection
 * @method Genre               setProductionGenre() Sets the current record's "ProductionGenre" collection
 * 
 * @package    bristol-old-vic-archive
 * @subpackage model
 * @author     Steve Lacey
 * @version    SVN: $Id$
 */
abstract class BaseGenre extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('genre');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));

        $this->option('orderBy', 'name asc');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Production as Productions', array(
             'refClass' => 'ProductionGenre',
             'local' => 'genre_id',
             'foreign' => 'production_id'));

        $this->hasMany('ProductionGenre', array(
             'local' => 'id',
             'foreign' => 'genre_id'));
    }
}