<?php

/**
 * BasePerson
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $email
 * @property string $telephone
 * 
 * @method string getName()      Returns the current record's "name" value
 * @method string getEmail()     Returns the current record's "email" value
 * @method string getTelephone() Returns the current record's "telephone" value
 * @method Person setName()      Sets the current record's "name" value
 * @method Person setEmail()     Sets the current record's "email" value
 * @method Person setTelephone() Sets the current record's "telephone" value
 * 
 * @package    bristol-old-vic-archive
 * @subpackage model
 * @author     Steve Lacey
 * @version    SVN: $Id$
 */
abstract class BasePerson extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('person');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('email', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('telephone', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));

        $this->option('orderBy', 'name asc');
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}