<?php

/**
 * BaseProductionGenre
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $production_id
 * @property integer $genre_id
 * @property Production $Production
 * @property Genre $Genre
 * 
 * @method integer         getProductionId()  Returns the current record's "production_id" value
 * @method integer         getGenreId()       Returns the current record's "genre_id" value
 * @method Production      getProduction()    Returns the current record's "Production" value
 * @method Genre           getGenre()         Returns the current record's "Genre" value
 * @method ProductionGenre setProductionId()  Sets the current record's "production_id" value
 * @method ProductionGenre setGenreId()       Sets the current record's "genre_id" value
 * @method ProductionGenre setProduction()    Sets the current record's "Production" value
 * @method ProductionGenre setGenre()         Sets the current record's "Genre" value
 * 
 * @package    bristol-old-vic-archive
 * @subpackage model
 * @author     Steve Lacey
 * @version    SVN: $Id$
 */
abstract class BaseProductionGenre extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('production_genre');
        $this->hasColumn('production_id', 'integer', 20, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 20,
             ));
        $this->hasColumn('genre_id', 'integer', 20, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 20,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Production', array(
             'local' => 'production_id',
             'foreign' => 'id'));

        $this->hasOne('Genre', array(
             'local' => 'genre_id',
             'foreign' => 'id'));
    }
}