<?php

/**
 * BaseProductionType
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $production_id
 * @property integer $type_id
 * @property Production $Production
 * @property Type $Type
 * 
 * @method integer        getProductionId()  Returns the current record's "production_id" value
 * @method integer        getTypeId()        Returns the current record's "type_id" value
 * @method Production     getProduction()    Returns the current record's "Production" value
 * @method Type           getType()          Returns the current record's "Type" value
 * @method ProductionType setProductionId()  Sets the current record's "production_id" value
 * @method ProductionType setTypeId()        Sets the current record's "type_id" value
 * @method ProductionType setProduction()    Sets the current record's "Production" value
 * @method ProductionType setType()          Sets the current record's "Type" value
 * 
 * @package    bristol-old-vic-archive
 * @subpackage model
 * @author     Steve Lacey
 * @version    SVN: $Id$
 */
abstract class BaseProductionType extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('production_type');
        $this->hasColumn('production_id', 'integer', 20, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 20,
             ));
        $this->hasColumn('type_id', 'integer', 20, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 20,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Production', array(
             'local' => 'production_id',
             'foreign' => 'id'));

        $this->hasOne('Type', array(
             'local' => 'type_id',
             'foreign' => 'id'));
    }
}