<?php

/**
 * BaseVenue
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $telephone
 * @property Doctrine_Collection $Layouts
 * 
 * @method string              getName()      Returns the current record's "name" value
 * @method string              getTelephone() Returns the current record's "telephone" value
 * @method Doctrine_Collection getLayouts()   Returns the current record's "Layouts" collection
 * @method Venue               setName()      Sets the current record's "name" value
 * @method Venue               setTelephone() Sets the current record's "telephone" value
 * @method Venue               setLayouts()   Sets the current record's "Layouts" collection
 * 
 * @package    bristol-old-vic-archive
 * @subpackage model
 * @author     Steve Lacey
 * @version    SVN: $Id$
 */
abstract class BaseVenue extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('venue');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('telephone', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));

        $this->option('orderBy', 'name asc');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Layout as Layouts', array(
             'local' => 'id',
             'foreign' => 'venue_id'));
    }
}