<?php

/**
 * BaseShow
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $performance_id
 * @property timestamp $show_at
 * @property integer $adult_tickets_sold
 * @property integer $adult_attendees
 * @property integer $child_tickets_sold
 * @property integer $child_attendees
 * @property integer $complimentary_tickets_sold
 * @property integer $student_tickets_sold
 * @property integer $student_attendees
 * @property Performance $Performance
 * 
 * @method integer     getPerformanceId()              Returns the current record's "performance_id" value
 * @method timestamp   getShowAt()                     Returns the current record's "show_at" value
 * @method integer     getAdultTicketsSold()           Returns the current record's "adult_tickets_sold" value
 * @method integer     getAdultAttendees()             Returns the current record's "adult_attendees" value
 * @method integer     getChildTicketsSold()           Returns the current record's "child_tickets_sold" value
 * @method integer     getChildAttendees()             Returns the current record's "child_attendees" value
 * @method integer     getComplimentaryTicketsSold()   Returns the current record's "complimentary_tickets_sold" value
 * @method integer     getStudentTicketsSold()         Returns the current record's "student_tickets_sold" value
 * @method integer     getStudentAttendees()           Returns the current record's "student_attendees" value
 * @method Performance getPerformance()                Returns the current record's "Performance" value
 * @method Show        setPerformanceId()              Sets the current record's "performance_id" value
 * @method Show        setShowAt()                     Sets the current record's "show_at" value
 * @method Show        setAdultTicketsSold()           Sets the current record's "adult_tickets_sold" value
 * @method Show        setAdultAttendees()             Sets the current record's "adult_attendees" value
 * @method Show        setChildTicketsSold()           Sets the current record's "child_tickets_sold" value
 * @method Show        setChildAttendees()             Sets the current record's "child_attendees" value
 * @method Show        setComplimentaryTicketsSold()   Sets the current record's "complimentary_tickets_sold" value
 * @method Show        setStudentTicketsSold()         Sets the current record's "student_tickets_sold" value
 * @method Show        setStudentAttendees()           Sets the current record's "student_attendees" value
 * @method Show        setPerformance()                Sets the current record's "Performance" value
 * 
 * @package    bristol-old-vic-archive
 * @subpackage model
 * @author     Steve Lacey
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseShow extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('`show`');
        $this->hasColumn('performance_id', 'integer', 20, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => '20',
             ));
        $this->hasColumn('show_at', 'timestamp', null, array(
             'type' => 'timestamp',
             'notnull' => true,
             'length' => '',
             ));
        $this->hasColumn('adult_tickets_sold', 'integer', 20, array(
             'type' => 'integer',
             'length' => '20',
             ));
        $this->hasColumn('adult_attendees', 'integer', 20, array(
             'type' => 'integer',
             'length' => '20',
             ));
        $this->hasColumn('child_tickets_sold', 'integer', 20, array(
             'type' => 'integer',
             'length' => '20',
             ));
        $this->hasColumn('child_attendees', 'integer', 20, array(
             'type' => 'integer',
             'length' => '20',
             ));
        $this->hasColumn('complimentary_tickets_sold', 'integer', 20, array(
             'type' => 'integer',
             'length' => '20',
             ));
        $this->hasColumn('student_tickets_sold', 'integer', 20, array(
             'type' => 'integer',
             'length' => '20',
             ));
        $this->hasColumn('student_attendees', 'integer', 20, array(
             'type' => 'integer',
             'length' => '20',
             ));

        $this->option('orderBy', 'performance_at asc');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Performance', array(
             'local' => 'performance_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}