<?php

/**
 * BaseProductionType
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property Doctrine_Collection $Productions
 * 
 * @method string              getName()        Returns the current record's "name" value
 * @method Doctrine_Collection getProductions() Returns the current record's "Productions" collection
 * @method ProductionType      setName()        Sets the current record's "name" value
 * @method ProductionType      setProductions() Sets the current record's "Productions" collection
 * 
 * @package    bristol-old-vic-archive
 * @subpackage model
 * @author     Steve Lacey
 * @version    SVN: $Id$
 */
abstract class BaseProductionType extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('production_type');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));

        $this->option('orderBy', 'name asc');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Production as Productions', array(
             'local' => 'id',
             'foreign' => 'production_type_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}