<?php

/**
 * BaseVenue
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $email
 * @property string $telephone
 * @property string $mobile
 * @property string $address_line_1
 * @property string $address_line_2
 * @property string $address_line_3
 * @property string $address_line_4
 * @property string $post_code
 * @property Doctrine_Collection $Layouts
 * 
 * @method string              getName()           Returns the current record's "name" value
 * @method string              getEmail()          Returns the current record's "email" value
 * @method string              getTelephone()      Returns the current record's "telephone" value
 * @method string              getMobile()         Returns the current record's "mobile" value
 * @method string              getAddressLine1()   Returns the current record's "address_line_1" value
 * @method string              getAddressLine2()   Returns the current record's "address_line_2" value
 * @method string              getAddressLine3()   Returns the current record's "address_line_3" value
 * @method string              getAddressLine4()   Returns the current record's "address_line_4" value
 * @method string              getPostCode()       Returns the current record's "post_code" value
 * @method Doctrine_Collection getLayouts()        Returns the current record's "Layouts" collection
 * @method Venue               setName()           Sets the current record's "name" value
 * @method Venue               setEmail()          Sets the current record's "email" value
 * @method Venue               setTelephone()      Sets the current record's "telephone" value
 * @method Venue               setMobile()         Sets the current record's "mobile" value
 * @method Venue               setAddressLine1()   Sets the current record's "address_line_1" value
 * @method Venue               setAddressLine2()   Sets the current record's "address_line_2" value
 * @method Venue               setAddressLine3()   Sets the current record's "address_line_3" value
 * @method Venue               setAddressLine4()   Sets the current record's "address_line_4" value
 * @method Venue               setPostCode()       Sets the current record's "post_code" value
 * @method Venue               setLayouts()        Sets the current record's "Layouts" collection
 * 
 * @package    bristol-old-vic-archive
 * @subpackage model
 * @author     Steve Lacey
 * @version    SVN: $Id$
 */
abstract class BaseVenue extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('venue');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('email', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('telephone', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('mobile', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('address_line_1', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('address_line_2', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('address_line_3', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('address_line_4', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('post_code', 'string', 20, array(
             'type' => 'string',
             'length' => 20,
             ));

        $this->option('orderBy', 'name asc');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Layout as Layouts', array(
             'local' => 'id',
             'foreign' => 'venue_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}