<?php

/**
 * BaseSponsor
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property Doctrine_Collection $Productions
 * @property Doctrine_Collection $ProductionSponsor
 * 
 * @method string              getName()              Returns the current record's "name" value
 * @method Doctrine_Collection getProductions()       Returns the current record's "Productions" collection
 * @method Doctrine_Collection getProductionSponsor() Returns the current record's "ProductionSponsor" collection
 * @method Sponsor             setName()              Sets the current record's "name" value
 * @method Sponsor             setProductions()       Sets the current record's "Productions" collection
 * @method Sponsor             setProductionSponsor() Sets the current record's "ProductionSponsor" collection
 * 
 * @package    bristol-old-vic-archive
 * @subpackage model
 * @author     Steve Lacey
 * @version    SVN: $Id$
 */
abstract class BaseSponsor extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sponsor');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));

        $this->option('orderBy', 'name asc');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Production as Productions', array(
             'refClass' => 'ProductionSponsor',
             'local' => 'sponsor_id',
             'foreign' => 'production_id'));

        $this->hasMany('ProductionSponsor', array(
             'local' => 'id',
             'foreign' => 'sponsor_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}