<?php

/**
 * BaseImage
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $title
 * @property string $caption
 * @property integer $production_id
 * @property integer $person_id
 * @property string $path
 * @property Production $Production
 * @property Person $Person
 * @property Doctrine_Collection $Productions
 * 
 * @method string              getTitle()         Returns the current record's "title" value
 * @method string              getCaption()       Returns the current record's "caption" value
 * @method integer             getProductionId()  Returns the current record's "production_id" value
 * @method integer             getPersonId()      Returns the current record's "person_id" value
 * @method string              getPath()          Returns the current record's "path" value
 * @method Production          getProduction()    Returns the current record's "Production" value
 * @method Person              getPerson()        Returns the current record's "Person" value
 * @method Doctrine_Collection getProductions()   Returns the current record's "Productions" collection
 * @method Image               setTitle()         Sets the current record's "title" value
 * @method Image               setCaption()       Sets the current record's "caption" value
 * @method Image               setProductionId()  Sets the current record's "production_id" value
 * @method Image               setPersonId()      Sets the current record's "person_id" value
 * @method Image               setPath()          Sets the current record's "path" value
 * @method Image               setProduction()    Sets the current record's "Production" value
 * @method Image               setPerson()        Sets the current record's "Person" value
 * @method Image               setProductions()   Sets the current record's "Productions" collection
 * 
 * @package    bristol-old-vic-archive
 * @subpackage model
 * @author     Steve Lacey
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseImage extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('image');
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '255',
             ));
        $this->hasColumn('caption', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('production_id', 'integer', 20, array(
             'type' => 'integer',
             'length' => '20',
             ));
        $this->hasColumn('person_id', 'integer', 20, array(
             'type' => 'integer',
             'length' => '20',
             ));
        $this->hasColumn('path', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '255',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Production', array(
             'local' => 'production_id',
             'foreign' => 'id'));

        $this->hasOne('Person', array(
             'local' => 'person_id',
             'foreign' => 'id'));

        $this->hasMany('Production as Productions', array(
             'local' => 'id',
             'foreign' => 'image_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'unique' => true,
             'fields' => 
             array(
              0 => 'title',
             ),
             'canUpdate' => true,
             ));
        $this->actAs($timestampable0);
        $this->actAs($sluggable0);
    }
}