<?php

/**
 * BaseStaff
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property Doctrine_Collection $Productions
 * @property Doctrine_Collection $Roles
 * @property ProductionStaff $ProductionStaff
 * 
 * @method Doctrine_Collection getProductions()     Returns the current record's "Productions" collection
 * @method Doctrine_Collection getRoles()           Returns the current record's "Roles" collection
 * @method ProductionStaff     getProductionStaff() Returns the current record's "ProductionStaff" value
 * @method Staff               setProductions()     Sets the current record's "Productions" collection
 * @method Staff               setRoles()           Sets the current record's "Roles" collection
 * @method Staff               setProductionStaff() Sets the current record's "ProductionStaff" value
 * 
 * @package    bristol-old-vic-archive
 * @subpackage model
 * @author     Steve Lacey
 * @version    SVN: $Id$
 */
abstract class BaseStaff extends Person
{
    public function setTableDefinition()
    {
        parent::setTableDefinition();
        $this->setTableName('staff');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Production as Productions', array(
             'refClass' => 'ProductionStaff',
             'local' => 'staff_id',
             'foreign' => 'production_id'));

        $this->hasMany('Role as Roles', array(
             'refClass' => 'ProductionStaff',
             'local' => 'staff_id',
             'foreign' => 'role_id'));

        $this->hasOne('ProductionStaff', array(
             'local' => 'id',
             'foreign' => 'staff_id',
             'onDelete' => 'cascade',
             'cascade' => array(
             0 => 'delete',
             )));
    }
}