<?php

/**
 * BasePerson
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property integer $image_id
 * @property string $email
 * @property string $telephone
 * @property enum $gender
 * @property Image $Image
 * @property Doctrine_Collection $Characters
 * @property Doctrine_Collection $Images
 * 
 * @method string              getName()       Returns the current record's "name" value
 * @method integer             getImageId()    Returns the current record's "image_id" value
 * @method string              getEmail()      Returns the current record's "email" value
 * @method string              getTelephone()  Returns the current record's "telephone" value
 * @method enum                getGender()     Returns the current record's "gender" value
 * @method Image               getImage()      Returns the current record's "Image" value
 * @method Doctrine_Collection getCharacters() Returns the current record's "Characters" collection
 * @method Doctrine_Collection getImages()     Returns the current record's "Images" collection
 * @method Person              setName()       Sets the current record's "name" value
 * @method Person              setImageId()    Sets the current record's "image_id" value
 * @method Person              setEmail()      Sets the current record's "email" value
 * @method Person              setTelephone()  Sets the current record's "telephone" value
 * @method Person              setGender()     Sets the current record's "gender" value
 * @method Person              setImage()      Sets the current record's "Image" value
 * @method Person              setCharacters() Sets the current record's "Characters" collection
 * @method Person              setImages()     Sets the current record's "Images" collection
 * 
 * @package    bristol-old-vic-archive
 * @subpackage model
 * @author     Steve Lacey
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePerson extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('person');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '255',
             ));
        $this->hasColumn('image_id', 'integer', 20, array(
             'type' => 'integer',
             'length' => '20',
             ));
        $this->hasColumn('email', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('telephone', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('gender', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'Male',
              1 => 'Female',
             ),
             'notnull' => true,
             ));

        $this->option('orderBy', 'name asc');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Image', array(
             'local' => 'image_id',
             'foreign' => 'id'));

        $this->hasMany('Character as Characters', array(
             'local' => 'id',
             'foreign' => 'actor_id'));

        $this->hasMany('Image as Images', array(
             'local' => 'id',
             'foreign' => 'person_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}