<?php

/**
 * BaseStaff
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * 
 * @package    bristol-old-vic-archive
 * @subpackage model
 * @author     Steve Lacey
 * @version    SVN: $Id$
 */
abstract class BaseStaff extends Person
{
    public function setTableDefinition()
    {
        parent::setTableDefinition();
        $this->setTableName('staff');
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}