# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/11-App

all:
  organisation:
    name: Bristol Old Vic
    website: http://www.bristololdvic.org.uk

  developer:
    name: Steve Lacey
    website: http://www.stevelacey.net

  data:
    date_format: "F Y"

  forms:
    min_production_character_forms: 5
    min_production_character_blank_forms: 2

  sf_admin_dash:
    site: Bristol Old Vic Archive
    include_jquery: false
    categories:
      Productions:
        items:
          Productions:
            url: production
            image: production
          Companies:
            url: company
            image: companies
          Collaborations:
            url: collaboration
            image: collaboration
          Funders:
            url: funder
            image: funder
          Genres:
            url: genre
            image: genre
          Types:
            url: type
            image: mediamanager
          Venues:
            url: venue
            image: frontpage
      Personnel:
        items:
          Performers:
            url: performer
            image: language
          Departments:
            url: department
            image: departments
          Roles:
            url: role
            image: roles
          Staff / Creative:
            url: staff
            image: addusers
          Users:
            url: user
            image: users
      Users:
        items:
           User Manual:
             url: /docs/user-manual.pdf
             image: manual
           Technical Document:
             url: /docs/technical-document.pdf
             image: technical

  sfImageTransformPlugin:
    default_adapter: ImageMagick # GD or ImageMagick
    mime_type:
      auto_detect: true
      library: gd_mime_type #  gd_mime_type (GD), Fileinfo (PECL), MIME_Type (PEAR)

dev:
  sfImageTransformPlugin:
    default_adapter: GD