# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/11-App

all:
  sf_admin_dash:
    site: Bristol Old Vic Archive
    include_jquery: false
    categories:
      Productions:
        items:
          Production:
            name: Productions
            url: production
            image: addedit
          Company:
            name: Companies
            url: company
            image: support
          Collaboration:
            name: Collaboration
            url: collaboration
            image: support
          Genre:
            name: Genres
            url: genre
            image: categories
          Type:
            name: Types
            url: type
            image: mediamanager
          Venue:
            name: Venues
            url: venue
            image: frontpage
      Personnel:
        items:
          Performers:
            name: Performers
            url: performer
            image: addusers
          Characters:
            name: Characters
            url: character
            image: language
          Departments:
            url: department
            image: folder-icon
          Roles:
            url: role
            image: users
          Staff:
            url: staff
            image: users
      Images:
        items:
          Images:
            name: Image Management
            url: image
            image: templatemanager
      Users:
        items:
          Users:
            name: User Management
            url: user
            image: users