# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/11-App

all:
  organisation:
    name: Bristol Old Vic
    website: http://www.bristololdvic.org.uk

  developer:
    name: Steve Lacey
    website: http://www.stevelacey.net

  data:
    date_format: "F Y"

  sf_admin_dash:
    site: Bristol Old Vic Archive
    include_jquery: false
    categories:
      Productions:
        items:
          Productions:
            url: production
            image: addedit
          Companies:
            url: company
            image: impressions
          Collaborations:
            url: collaboration
            image: support
          Funders:
            url: funder
            image: generic
          Genres:
            url: genre
            image: categories
          Types:
            url: type
            image: mediamanager
          Venues:
            url: venue
            image: frontpage
      Personnel:
        items:
          Performers:
            url: performer
            image: language
          Departments:
            url: department
            image: folder-icon
          Roles:
            url: role
            image: users
          Staff / Creative:
            url: staff
            image: addusers
      Users:
        items:
          Users:
            url: user
            image: users

  sfImageTransformPlugin:
    default_adapter: ImageMagick # GD or ImageMagick
    mime_type:
      auto_detect: true
      library: gd_mime_type #  gd_mime_type (GD), Fileinfo (PECL), MIME_Type (PEAR)

dev:
  sfImageTransformPlugin:
    default_adapter: GD