sponsor:
  class: sfDoctrineRouteCollection
  options:
    model:                Sponsor
    module:               sponsor
    prefix_path:          /sponsor
    column:               id
    with_wildcard_routes: true

collaboration:
  class: sfDoctrineRouteCollection
  options:
    model:                Collaboration
    module:               collaboration
    prefix_path:          /collaboration
    column:               id
    with_wildcard_routes: true

staff:
  class: sfDoctrineRouteCollection
  options:
    model:                Staff
    module:               staff
    prefix_path:          /staff
    column:               id
    with_wildcard_routes: true

role:
  class: sfDoctrineRouteCollection
  options:
    model:                Role
    module:               role
    prefix_path:          /role
    column:               id
    with_wildcard_routes: true

department:
  class: sfDoctrineRouteCollection
  options:
    model:                Department
    module:               department
    prefix_path:          /department
    column:               id
    with_wildcard_routes: true

type:
  class: sfDoctrineRouteCollection
  options:
    model:                Type
    module:               type
    prefix_path:          /type
    column:               id
    with_wildcard_routes: true

company:
  class: sfDoctrineRouteCollection
  options:
    model:                Company
    module:               company
    prefix_path:          /company
    column:               id
    with_wildcard_routes: true

user:
  class: sfDoctrineRouteCollection
  options:
    model:                sfGuardUser
    module:               user
    prefix_path:          /user
    column:               id
    with_wildcard_routes: true

image:
  class: sfDoctrineRouteCollection
  options:
    model:                Image
    module:               image
    prefix_path:          /image
    column:               id
    with_wildcard_routes: true

image_show:
  class: sfDoctrineRoute
  url: /images/uploads/:dimensions/:slug.:sf_format
  options:
    model: Image
    type: object
    generate_shortest_url: false
  param:
    module: image
    action: show
    sf_format: png
  requirements:
    dimensions: \d+x\d+

genre:
  class: sfDoctrineRouteCollection
  options:
    model:                Genre
    module:               genre
    prefix_path:          /genre
    column:               id
    with_wildcard_routes: true

venue:
  class: sfDoctrineRouteCollection
  options:
    model:                Venue
    module:               venue
    prefix_path:          /venue
    column:               id
    with_wildcard_routes: true

performer:
  class: sfDoctrineRouteCollection
  options:
    model:                Performer
    module:               performer
    prefix_path:          /performer
    column:               id
    with_wildcard_routes: true

production:
  class: sfDoctrineRouteCollection
  options:
    model:                Production
    module:               production
    prefix_path:          /production
    column:               id
    with_wildcard_routes: true

# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
homepage:
  url:   /
  param: { module: sfAdminDash, action: dashboard }

sf_guard_signin:
  url:   /login
  param: { module: sfGuardAuth, action: signin }

sf_guard_signout:
  url:   /logout
  param: { module: sfGuardAuth, action: signout }

sf_guard_password:
  url:   /request_password
  param: { module: sfGuardAuth, action: password }

# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*