# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    title:        Bristol Old Vic Archive
    description:  Bristol Old Vic Archive
    keywords:     bristol, old, vic, archive
    language:     en
    robots:       index, follow

  stylesheets:
    - main.css
    - print.css: { media: print }
    - jquery.facebox.css
    - jquery.fancybox-1.3.4.css

  javascripts:
    - http://ajax.googleapis.com/ajax/libs/jquery/1.8/jquery.min.js
    - jquery.facebox.js
    - jquery.dirtyforms.js
    - jquery.easing-1.3.pack.js
    - jquery.mousewheel-3.0.4.pack.js
    - jquery.fancybox-1.3.4.pack.js
    - main.js

  has_layout:     true
  layout:         layout
