<?php

/**
 * Department
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    bristol-old-vic-archive
 * @subpackage model
 * @author     Steve Lacey
 * @version    SVN: $Id$
 */
class Department extends BaseDepartment
{
}
