<?php

/**
 * Funder
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    bristol-old-vic-archive
 * @subpackage model
 * @author     Steve Lacey
 * @version    SVN: $Id$
 */
class Funder extends BaseFunder {
  public function getProductionDonations(Production $production) {
    return Doctrine::getTable('Donation')->findByProductionFunder($production, $this);
  }
}