<?php

/**
 * Sponsor
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    bristol-old-vic-archive
 * @subpackage model
 * @author     Steve Lacey
 * @version    SVN: $Id$
 */
class Sponsor extends BaseSponsor
{
}
