generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Role
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          role
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        title: Roles
        display:
          - =name
          - department
      filter:
        display:
          - name
          - department_id
      form:    ~
      edit:
        title: %%name%%
      new:     ~