generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Genre
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          genre
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields: ~
      list:
        title: Genres
        display:
          - =name
      filter:
        display:
          - name
      form:    ~
      edit:
        title: %%name%%
      new:     ~