generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Venue
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          venue
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        title: Venues
        display:
          - =name
          - telephone
      filter:
        display:
          - name
      form:
       display:
        "Basic Details":
          - name
          - email
          - telephone
          - mobile
          - address_line_1
          - address_line_2
          - address_line_3
          - address_line_4
          - post_code
          - notes
        "Layouts":
          - layouts
      edit:
        title: %%name%%

      new:     ~