<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version2 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('production_genre', 'production_genre_production_id_production_id', array(
             'name' => 'production_genre_production_id_production_id',
             'local' => 'production_id',
             'foreign' => 'id',
             'foreignTable' => 'production',
             ));
        $this->createForeignKey('production_genre', 'production_genre_genre_id_genre_id', array(
             'name' => 'production_genre_genre_id_genre_id',
             'local' => 'genre_id',
             'foreign' => 'id',
             'foreignTable' => 'genre',
             ));
        $this->createForeignKey('production_sponsor', 'production_sponsor_production_id_production_id', array(
             'name' => 'production_sponsor_production_id_production_id',
             'local' => 'production_id',
             'foreign' => 'id',
             'foreignTable' => 'production',
             ));
        $this->createForeignKey('production_sponsor', 'production_sponsor_sponsor_id_sponsor_id', array(
             'name' => 'production_sponsor_sponsor_id_sponsor_id',
             'local' => 'sponsor_id',
             'foreign' => 'id',
             'foreignTable' => 'sponsor',
             ));
        $this->createForeignKey('production_type', 'production_type_production_id_production_id', array(
             'name' => 'production_type_production_id_production_id',
             'local' => 'production_id',
             'foreign' => 'id',
             'foreignTable' => 'production',
             ));
        $this->createForeignKey('production_type', 'production_type_type_id_type_id', array(
             'name' => 'production_type_type_id_type_id',
             'local' => 'type_id',
             'foreign' => 'id',
             'foreignTable' => 'type',
             ));
    }

    public function down()
    {
        $this->dropForeignKey('production_genre', 'production_genre_production_id_production_id');
        $this->dropForeignKey('production_genre', 'production_genre_genre_id_genre_id');
        $this->dropForeignKey('production_sponsor', 'production_sponsor_production_id_production_id');
        $this->dropForeignKey('production_sponsor', 'production_sponsor_sponsor_id_sponsor_id');
        $this->dropForeignKey('production_type', 'production_type_production_id_production_id');
        $this->dropForeignKey('production_type', 'production_type_type_id_type_id');
    }
}