<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version1 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->dropForeignKey('production', 'production_production_type_id_production_type_id');
        $this->dropForeignKey('production', 'production_genre_id_genre_id');
        $this->renameTable('production_type', 'type');
        $this->createTable('production_type', array(
             'production_id' =>
             array(
              'type' => 'integer',
              'length' => '8',
              'primary' => '1',
             ),
             'type_id' =>
             array(
              'type' => 'integer',
              'length' => '8',
              'primary' => '1',
             ),
             ), array(
             'primary' =>
             array(
              0 => 'production_id',
              1 => 'type_id',
             ),
             ));
        $this->createTable('production_genre', array(
             'production_id' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'length' => '20',
             ),
             'genre_id' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'length' => '20',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'production_id',
              1 => 'genre_id',
             ),
             ));
        $this->createTable('production_sponsor', array(
             'production_id' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'length' => '20',
             ),
             'sponsor_id' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'length' => '20',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'production_id',
              1 => 'sponsor_id',
             ),
             ));
        $this->createTable('sponsor', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => '8',
              'autoincrement' => '1',
              'primary' => '1',
             ),
             'name' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '255',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
        $this->removeColumn('production', 'genre_id');
        $this->removeColumn('production', 'production_type_id');
    }

    public function down()
    {
        $this->dropTable('production_genre');
        $this->dropTable('production_sponsor');
        $this->dropTable('production_type');
        $this->dropTable('sponsor');
        $this->renameTable('type', 'production_type');
        $this->addColumn('production', 'genre_id', 'integer', '8', array());
        $this->addColumn('production', 'production_type_id', 'integer', '8', array());
        $this->createForeignKey('production', 'production_production_type_id_production_type_id', array(
             'name' => 'production_production_type_id_production_type_id',
             'local' => 'production_type_id',
             'foreign' => 'id',
             'foreignTable' => 'production_type',
             ));
        $this->createForeignKey('production', 'production_genre_id_genre_id', array(
             'name' => 'production_genre_id_genre_id',
             'local' => 'genre_id',
             'foreign' => 'id',
             'foreignTable' => 'genre',
             ));
    }
}