<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version1 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('company', 'mobile', 'string', '255', array(
             ));
        $this->addColumn('company', 'address_line_1', 'string', '255', array(
             ));
        $this->addColumn('company', 'address_line_2', 'string', '255', array(
             ));
        $this->addColumn('company', 'address_line_3', 'string', '255', array(
             ));
        $this->addColumn('company', 'address_line_4', 'string', '255', array(
             ));
        $this->addColumn('company', 'post_code', 'string', '20', array(
             ));
        $this->addColumn('venue', 'email', 'string', '255', array(
             ));
        $this->addColumn('venue', 'mobile', 'string', '255', array(
             ));
        $this->addColumn('venue', 'address_line_1', 'string', '255', array(
             ));
        $this->addColumn('venue', 'address_line_2', 'string', '255', array(
             ));
        $this->addColumn('venue', 'address_line_3', 'string', '255', array(
             ));
        $this->addColumn('venue', 'address_line_4', 'string', '255', array(
             ));
        $this->addColumn('venue', 'post_code', 'string', '20', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('company', 'mobile');
        $this->removeColumn('company', 'address_line_1');
        $this->removeColumn('company', 'address_line_2');
        $this->removeColumn('company', 'address_line_3');
        $this->removeColumn('company', 'address_line_4');
        $this->removeColumn('company', 'post_code');
        $this->removeColumn('venue', 'email');
        $this->removeColumn('venue', 'mobile');
        $this->removeColumn('venue', 'address_line_1');
        $this->removeColumn('venue', 'address_line_2');
        $this->removeColumn('venue', 'address_line_3');
        $this->removeColumn('venue', 'address_line_4');
        $this->removeColumn('venue', 'post_code');
    }
}