<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version10 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->dropForeignKey('production_sponsor', 'production_sponsor_production_id_production_id');
        $this->dropForeignKey('production_sponsor', 'production_sponsor_sponsor_id_sponsor_id');
        $this->dropTable('production_sponsor');
        $this->createTable('donation', array(
             'id' =>
             array(
              'type' => 'integer',
              'length' => '8',
              'autoincrement' => '1',
              'primary' => '1',
             ),
             'production_id' => 
             array(
              'type' => 'integer',
              'notnull' => '1',
              'length' => '20',
             ),
             'sponsor_id' => 
             array(
              'type' => 'integer',
              'notnull' => '1',
              'length' => '20',
             ),
             'donation' => 
             array(
              'type' => 'float',
              'length' => '',
             ),
             'description' => 
             array(
              'type' => 'string',
              'length' => '',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'production_id',
              1 => 'sponsor_id',
             ),
             ));
        $this->createForeignKey('donation', 'donation_production_id_production_id', array(
             'name' => 'donation_production_id_production_id',
             'local' => 'production_id',
             'foreign' => 'id',
             'foreignTable' => 'production',
             ));
        $this->createForeignKey('donation', 'donation_sponsor_id_sponsor_id', array(
             'name' => 'donation_sponsor_id_sponsor_id',
             'local' => 'sponsor_id',
             'foreign' => 'id',
             'foreignTable' => 'sponsor',
             ));
    }

    public function down()
    {
        $this->dropTable('donation');
        $this->createTable('production_sponsor', array(
             'production_id' =>
             array(
              'type' => 'integer',
              'primary' => '1',
              'length' => '20',
             ),
             'sponsor_id' =>
             array(
              'type' => 'integer',
              'primary' => '1',
              'length' => '20',
             ),
             'donation' =>
             array(
              'type' => 'float',
              'length' => '',
             ),
             'description' =>
             array(
              'type' => 'string',
              'length' => '',
             ),
             ), array(
             'primary' =>
             array(
              0 => 'production_id',
              1 => 'sponsor_id',
             ),
             ));
        $this->createForeignKey('production_sponsor', 'production_sponsor_production_id_production_id', array(
             'name' => 'production_sponsor_production_id_production_id',
             'local' => 'production_id',
             'foreign' => 'id',
             'foreignTable' => 'production',
             ));
        $this->createForeignKey('production_sponsor', 'production_sponsor_sponsor_id_sponsor_id', array(
             'name' => 'production_sponsor_sponsor_id_sponsor_id',
             'local' => 'sponsor_id',
             'foreign' => 'id',
             'foreignTable' => 'sponsor',
             ));
        $this->dropForeignKey('donation', 'donation_production_id_production_id');
        $this->dropForeignKey('donation', 'donation_sponsor_id_sponsor_id');
    }
}