<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version7 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->changeColumn('role', 'name', 'string', '255', array(
             'unique' => '1',
             'notnull' => '1',
             ));
    }

    public function down()
    {

    }
}