<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version8 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->removeColumn('production', 'funding');
        $this->addColumn('production', 'number_of_performances', 'integer', '20', array(
             ));
        $this->changeColumn('production', 'start_at', 'timestamp', '25', array(
             ));
        $this->changeColumn('production', 'end_at', 'timestamp', '25', array(
             ));
    }

    public function down()
    {
        $this->addColumn('production', 'funding', 'string', '', array(
             ));
        $this->removeColumn('production', 'number_of_performances');
    }
}