<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version9 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('production_sponsor', 'donation', 'float', '', array(
             ));
        $this->addColumn('production_sponsor', 'description', 'string', '', array(
             ));
        $this->addColumn('sponsor', 'description', 'string', '', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('production_sponsor', 'donation');
        $this->removeColumn('production_sponsor', 'description');
        $this->removeColumn('sponsor', 'description');
    }
}