<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version8 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->dropTable('production_staff');
        $this->createTable('production_staff', array(
             'id' =>
             array(
              'type' => 'integer',
             'autoincrement' => '1',
             'primary' => '1',
              'length' => '20',
             ),
             'production_id' =>
             array(
              'type' => 'integer',
              'notnull' => '1',
              'length' => '20',
             ),
             'role_id' =>
             array(
              'type' => 'integer',
              'notnull' => '1',
              'length' => '20',
             ),
             'staff_id' =>
             array(
              'type' => 'integer',
              'notnull' => '1',
              'length' => '20',
             )
        ));
        $this->addIndex('production_staff', 'production_id_role_id', array(
             'fields' =>
             array(
              0 => 'production_id',
              1 => 'role_id',
             ),
             'type' => 'unique',
             ));
        $this->createForeignKey('production_staff', 'production_staff_production_id_production_id', array(
             'name' => 'production_staff_production_id_production_id',
             'local' => 'production_id',
             'foreign' => 'id',
             'foreignTable' => 'production',
             ));
        $this->createForeignKey('production_staff', 'production_staff_role_id_role_id', array(
             'name' => 'production_staff_role_id_role_id',
             'local' => 'role_id',
             'foreign' => 'id',
             'foreignTable' => 'role',
             ));
        $this->createForeignKey('production_staff', 'production_staff_staff_id_staff_id', array(
             'name' => 'production_staff_staff_id_staff_id',
             'local' => 'staff_id',
             'foreign' => 'id',
             'foreignTable' => 'staff',
             ));
        $this->addIndex('production_staff', 'production_staff_production_id', array(
             'fields' =>
             array(
              0 => 'production_id',
             ),
             ));
        $this->addIndex('production_staff', 'production_staff_role_id', array(
             'fields' =>
             array(
              0 => 'role_id',
             ),
             ));
        $this->addIndex('production_staff', 'production_staff_staff_id', array(
             'fields' =>
             array(
              0 => 'staff_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('production_staff');
        $this->createTable('production_staff', array(
             'production_id' =>
             array(
              'type' => 'integer',
              'primary' => '1',
              'length' => '20',
             ),
             'role_id' =>
             array(
              'type' => 'integer',
              'primary' => '1',
              'length' => '20',
             ),
             'staff_id' =>
             array(
              'type' => 'integer',
              'notnull' => '1',
              'length' => '20',
             ),
             ), array(
             'primary' =>
             array(
              0 => 'production_id',
              1 => 'role_id',
             ),
             ));
        $this->createForeignKey('production_staff', 'production_staff_production_id_production_id', array(
             'name' => 'production_staff_production_id_production_id',
             'local' => 'production_id',
             'foreign' => 'id',
             'foreignTable' => 'production',
             ));
        $this->createForeignKey('production_staff', 'production_staff_role_id_role_id', array(
             'name' => 'production_staff_role_id_role_id',
             'local' => 'role_id',
             'foreign' => 'id',
             'foreignTable' => 'role',
             ));
        $this->createForeignKey('production_staff', 'production_staff_staff_id_staff_id', array(
             'name' => 'production_staff_staff_id_staff_id',
             'local' => 'staff_id',
             'foreign' => 'id',
             'foreignTable' => 'staff',
             ));
        $this->addIndex('production_staff', 'production_staff_production_id', array(
             'fields' =>
             array(
              0 => 'production_id',
             ),
             ));
        $this->addIndex('production_staff', 'production_staff_role_id', array(
             'fields' =>
             array(
              0 => 'role_id',
             ),
             ));
        $this->addIndex('production_staff', 'production_staff_staff_id', array(
             'fields' =>
             array(
              0 => 'staff_id',
             ),
             ));
    }
}