<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version16 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->dropForeignKey('donation', 'donation_sponsor_id_sponsor_id');
        $this->dropTable('sponsor');
        $this->createTable('funder', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => '8',
              'autoincrement' => '1',
              'primary' => '1',
             ),
             'name' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '255',
             ),
             'description' => 
             array(
              'type' => 'string',
              'length' => '',
             ),
             'created_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             'updated_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
        $this->removeColumn('donation', 'sponsor_id');
        $this->addColumn('donation', 'funder_id', 'integer', '20', array(
             'notnull' => '1',
             ));
        $this->createForeignKey('donation', 'donation_funder_id_funder_id', array(
             'name' => 'donation_funder_id_funder_id',
             'local' => 'funder_id',
             'foreign' => 'id',
             'foreignTable' => 'funder',
             ));
    }

    public function down()
    {
        $this->dropForeignKey('donation', 'donation_funder_id_funder_id');
        $this->createTable('sponsor', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => '8',
              'autoincrement' => '1',
              'primary' => '1',
             ),
             'name' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '255',
             ),
             'description' => 
             array(
              'type' => 'string',
              'length' => '',
             ),
             'created_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             'updated_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             ), array(
             'type' => '',
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => '',
             'charset' => '',
             ));
        $this->dropTable('funder');
        $this->addColumn('donation', 'sponsor_id', 'integer', '20', array(
             'notnull' => '1',
             ));
        $this->removeColumn('donation', 'funder_id');
        $this->createForeignKey('donation', 'donation_sponsor_id_sponsor_id', array(
             'name' => 'donation_sponsor_id_sponsor_id',
             'local' => 'sponsor_id',
             'foreign' => 'id',
             'foreignTable' => 'sponsor',
             ));
    }
}