<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version17 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('production', 'matinee_performance_time', 'time', '25', array(
             ));
        $this->addColumn('production', 'evening_performance_time', 'time', '25', array(
             ));
        $this->addColumn('production', 'various_performance_times', 'boolean', '25', array(
             'default' => '0',
             ));
    }

    public function down()
    {
        $this->removeColumn('production', 'matinee_performance_time');
        $this->removeColumn('production', 'evening_performance_time');
        $this->removeColumn('production', 'various_performance_times');
    }
}