<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version18 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->removeColumn('performer', 'email');
        $this->removeColumn('performer', 'telephone');
        $this->removeColumn('person', 'email');
        $this->removeColumn('person', 'telephone');
        $this->removeColumn('staff', 'email');
        $this->removeColumn('staff', 'telephone');
    }

    public function down()
    {
        $this->addColumn('performer', 'email', 'string', '255', array(
             ));
        $this->addColumn('performer', 'telephone', 'string', '255', array(
             ));
        $this->addColumn('person', 'email', 'string', '255', array(
             ));
        $this->addColumn('person', 'telephone', 'string', '255', array(
             ));
        $this->addColumn('staff', 'email', 'string', '255', array(
             ));
        $this->addColumn('staff', 'telephone', 'string', '255', array(
             ));
    }
}