<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version20 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->removeColumn('production', 'adult_ticket_price');
        $this->removeColumn('production', 'child_ticket_price');
        $this->removeColumn('production', 'student_ticket_price');
        $this->addColumn('production', 'seating', 'enum', '', array(
             'values' => 
             array(
              0 => 'Reserved',
              1 => 'Partially Reserved',
              2 => 'Not Reserved',
             ),
             ));
        $this->addColumn('production', 'full_ticket_min_price', 'float', '', array(
             ));
        $this->addColumn('production', 'full_ticket_max_price', 'float', '', array(
             ));
        $this->addColumn('production', 'concessionary_ticket_min_price', 'float', '', array(
             ));
        $this->addColumn('production', 'concessionary_ticket_max_price', 'float', '', array(
             ));
    }

    public function down()
    {
        $this->addColumn('production', 'adult_ticket_price', 'float', '', array(
             ));
        $this->addColumn('production', 'child_ticket_price', 'float', '', array(
             ));
        $this->addColumn('production', 'student_ticket_price', 'float', '', array(
             ));
        $this->removeColumn('production', 'seating');
        $this->removeColumn('production', 'full_ticket_min_price');
        $this->removeColumn('production', 'full_ticket_max_price');
        $this->removeColumn('production', 'concessionary_ticket_min_price');
        $this->removeColumn('production', 'concessionary_ticket_max_price');
    }
}