<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version19 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('venue', 'notes', 'string', '', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('venue', 'notes');
    }
}