<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version23 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->dropForeignKey('production', 'production_type_id_type_id');
        $this->dropForeignKey('production', 'production_genre_id_genre_id');
        $this->dropForeignKey('production', 'production_company_id_company_id');
        $this->dropForeignKey('production', 'production_collaboration_id_collaboration_id');
        $this->createForeignKey('production', 'production_type_id_type_id_1', array(
             'name' => 'production_type_id_type_id_1',
             'local' => 'type_id',
             'foreign' => 'id',
             'foreignTable' => 'type',
             'onUpdate' => '',
             'onDelete' => 'set null',
             ));
        $this->createForeignKey('production', 'production_genre_id_genre_id_1', array(
             'name' => 'production_genre_id_genre_id_1',
             'local' => 'genre_id',
             'foreign' => 'id',
             'foreignTable' => 'genre',
             'onUpdate' => '',
             'onDelete' => 'set null',
             ));
        $this->createForeignKey('production', 'production_company_id_company_id_1', array(
             'name' => 'production_company_id_company_id_1',
             'local' => 'company_id',
             'foreign' => 'id',
             'foreignTable' => 'company',
             'onUpdate' => '',
             'onDelete' => 'set null',
             ));
        $this->createForeignKey('production', 'production_collaboration_id_collaboration_id_1', array(
             'name' => 'production_collaboration_id_collaboration_id_1',
             'local' => 'collaboration_id',
             'foreign' => 'id',
             'foreignTable' => 'collaboration',
             'onUpdate' => '',
             'onDelete' => 'set null',
             ));
        $this->addIndex('production', 'production_type_id', array(
             'fields' => 
             array(
              0 => 'type_id',
             ),
             ));
        $this->addIndex('production', 'production_genre_id', array(
             'fields' => 
             array(
              0 => 'genre_id',
             ),
             ));
        $this->addIndex('production', 'production_company_id', array(
             'fields' => 
             array(
              0 => 'company_id',
             ),
             ));
        $this->addIndex('production', 'production_collaboration_id', array(
             'fields' => 
             array(
              0 => 'collaboration_id',
             ),
             ));
    }

    public function down()
    {
        $this->removeIndex('production', 'production_type_id', array(
             'fields' =>
             array(
              0 => 'type_id',
             ),
             ));
        $this->removeIndex('production', 'production_genre_id', array(
             'fields' =>
             array(
              0 => 'genre_id',
             ),
             ));
        $this->removeIndex('production', 'production_company_id', array(
             'fields' =>
             array(
              0 => 'company_id',
             ),
             ));
        $this->removeIndex('production', 'production_collaboration_id', array(
             'fields' =>
             array(
              0 => 'collaboration_id',
             ),
             ));
        $this->dropForeignKey('production', 'production_type_id_type_id_1');
        $this->dropForeignKey('production', 'production_genre_id_genre_id_1');
        $this->dropForeignKey('production', 'production_company_id_company_id_1');
        $this->dropForeignKey('production', 'production_collaboration_id_collaboration_id_1');
        $this->createForeignKey('production', 'production_type_id_type_id', array(
             'name' => 'production_type_id_type_id',
             'local' => 'type_id',
             'foreign' => 'id',
             'foreignTable' => 'type',
             ));
        $this->createForeignKey('production', 'production_genre_id_genre_id', array(
             'name' => 'production_genre_id_genre_id',
             'local' => 'genre_id',
             'foreign' => 'id',
             'foreignTable' => 'genre',
             ));
        $this->createForeignKey('production', 'production_company_id_company_id', array(
             'name' => 'production_company_id_company_id',
             'local' => 'company_id',
             'foreign' => 'id',
             'foreignTable' => 'company',
             ));
        $this->createForeignKey('production', 'production_collaboration_id_collaboration_id', array(
             'name' => 'production_collaboration_id_collaboration_id',
             'local' => 'collaboration_id',
             'foreign' => 'id',
             'foreignTable' => 'collaboration',
             ));
    }
}