<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version26 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->dropForeignKey('performer', 'performer_image_id_image_id');
        $this->dropForeignKey('person', 'person_image_id_image_id');
        $this->dropForeignKey('staff', 'staff_image_id_image_id');
        $this->createForeignKey('performer', 'performer_image_id_image_id', array(
             'name' => 'performer_image_id_image_id',
             'local' => 'image_id',
             'foreign' => 'id',
             'foreignTable' => 'image',
             'onUpdate' => '',
             'onDelete' => 'cascade',
             ));
        $this->createForeignKey('person', 'person_image_id_image_id', array(
             'name' => 'person_image_id_image_id',
             'local' => 'image_id',
             'foreign' => 'id',
             'foreignTable' => 'image',
             'onUpdate' => '',
             'onDelete' => 'cascade',
             ));
        $this->createForeignKey('staff', 'staff_image_id_image_id', array(
             'name' => 'staff_image_id_image_id',
             'local' => 'image_id',
             'foreign' => 'id',
             'foreignTable' => 'image',
             'onUpdate' => '',
             'onDelete' => 'cascade',
             ));
    }

    public function down()
    {
        $this->dropForeignKey('performer', 'performer_image_id_image_id');
        $this->dropForeignKey('person', 'person_image_id_image_id');
        $this->dropForeignKey('staff', 'staff_image_id_image_id');
        $this->createForeignKey('performer', 'performer_image_id_image_id', array(
             'name' => 'performer_image_id_image_id',
             'local' => 'image_id',
             'foreign' => 'id',
             'foreignTable' => 'image',
             ));
        $this->createForeignKey('person', 'person_image_id_image_id', array(
             'name' => 'person_image_id_image_id',
             'local' => 'image_id',
             'foreign' => 'id',
             'foreignTable' => 'image',
             ));
        $this->createForeignKey('staff', 'staff_image_id_image_id', array(
             'name' => 'staff_image_id_image_id',
             'local' => 'image_id',
             'foreign' => 'id',
             'foreignTable' => 'image',
             ));
    }
}