<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version24 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->dropForeignKey('production', 'production_shot_image_id_image_id');
        $this->dropForeignKey('production', 'production_set_design_image_id_image_id');
        $this->createForeignKey('production', 'production_shot_image_id_image_id', array(
             'name' => 'production_shot_image_id_image_id',
             'local' => 'shot_image_id',
             'foreign' => 'id',
             'foreignTable' => 'image',
             'onUpdate' => '',
             'onDelete' => 'cascade',
             ));
        $this->createForeignKey('production', 'production_set_design_image_id_image_id', array(
             'name' => 'production_set_design_image_id_image_id',
             'local' => 'set_design_image_id',
             'foreign' => 'id',
             'foreignTable' => 'image',
             'onUpdate' => '',
             'onDelete' => 'cascade',
             ));
        $this->addIndex('production', 'production_shot_image_id', array(
             'fields' => 
             array(
              0 => 'shot_image_id',
             ),
             ));
        $this->addIndex('production', 'production_set_design_image_id', array(
             'fields' => 
             array(
              0 => 'set_design_image_id',
             ),
             ));
    }

    public function down()
    {
        $this->removeIndex('production', 'production_shot_image_id', array(
             'fields' =>
             array(
              0 => 'shot_image_id',
             ),
             ));
        $this->removeIndex('production', 'production_set_design_image_id', array(
             'fields' =>
             array(
              0 => 'set_design_image_id',
             ),
             ));
        $this->dropForeignKey('production', 'production_shot_image_id_image_id');
        $this->dropForeignKey('production', 'production_set_design_image_id_image_id');
        $this->createForeignKey('production', 'production_shot_image_id_image_id', array(
             'name' => 'production_shot_image_id_image_id',
             'local' => 'shot_image_id',
             'foreign' => 'id',
             'foreignTable' => 'image',
             ));
        $this->createForeignKey('production', 'production_set_design_image_id_image_id', array(
             'name' => 'production_set_design_image_id_image_id',
             'local' => 'set_design_image_id',
             'foreign' => 'id',
             'foreignTable' => 'image',
             ));
    }
}