<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version22 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->dropForeignKey('layout', 'layout_venue_id_venue_id');
        $this->dropForeignKey('production', 'production_layout_id_layout_id');
        $this->createForeignKey('layout', 'layout_venue_id_venue_id', array(
             'name' => 'layout_venue_id_venue_id',
             'local' => 'venue_id',
             'foreign' => 'id',
             'foreignTable' => 'venue',
             'onUpdate' => '',
             'onDelete' => 'cascade',
             ));
        $this->createForeignKey('production', 'production_layout_id_layout_id', array(
             'name' => 'production_layout_id_layout_id',
             'local' => 'layout_id',
             'foreign' => 'id',
             'foreignTable' => 'layout',
             'onUpdate' => '',
             'onDelete' => 'set null',
             ));
        $this->addIndex('layout', 'layout_venue_id', array(
             'fields' => 
             array(
              0 => 'venue_id',
             ),
             ));
        $this->addIndex('production', 'production_layout_id', array(
             'fields' => 
             array(
              0 => 'layout_id',
             ),
             ));
    }

    public function down()
    {
        $this->removeIndex('layout', 'layout_venue_id', array(
             'fields' => 
             array(
              0 => 'venue_id',
             ),
             ));
        $this->dropForeignKey('layout', 'layout_venue_id_venue_id');
        $this->dropForeignKey('production', 'production_layout_id_layout_id');
        $this->removeIndex('production', 'production_layout_id', array(
             'fields' =>
             array(
              0 => 'layout_id',
             ),
             ));
        $this->createForeignKey('layout', 'layout_venue_id_venue_id', array(
             'name' => 'layout_venue_id_venue_id',
             'local' => 'venue_id',
             'foreign' => 'id',
             'foreignTable' => 'venue',
             ));
        $this->createForeignKey('production', 'production_layout_id_layout_id', array(
             'name' => 'production_layout_id_layout_id',
             'local' => 'layout_id',
             'foreign' => 'id',
             'foreignTable' => 'layout',
             ));
    }
}