generator:
  class: sfDoctrineGenerator
  param:
    model_class:           sfGuardUser
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          user
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        title: Users
        display:
          - =name
          - username
          - email_address
          - created_at
          - last_login
      filter:
        display:
          - first_name
          - last_name
      form:
        class: sfGuardUserForm
        display:
          - first_name
          - last_name
          - email_address
          - username
          - password
          - password_again
          - is_super_admin
          - is_active
      edit:
        title: %%name%%
      new:     ~