generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Character
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          character
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        display:
          - =name
          - gender
      filter:
        display:
          - name
          - gender
          - actor_id
          - production_id
      form:    ~
      edit:    ~
      new:     ~