generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Sponsor
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          sponsor
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        display:
          - name
          - description
      filter:
        display:
          - name
          - productions_list
      form:    ~
      edit:    ~
      new:     ~
