generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Funder
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          funder
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        title: Funders
        display:
          - name
          - description
      filter:
        display:
          - name
          - productions_list
      form:    ~
      edit:
        title: %%name%%
      new:     ~