generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Performer
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          performer
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        title: Performers
        display:
          - =name
          - gender
          - email
          - telephone
      filter:
        display:
          - name
          - gender
      form:    ~
      edit:
        title: %%name%%
      new:     ~