generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Production
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          production
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        display:
          - =name
          - type
          - venue
          - start_at
          - end_at
          - company
        fields:
          start_at:
            label: Performance start
            date_format: d MMMM y
          end_at:
            label: Performance end
            date_format: d MMMM y
      filter:
        display:
          - name
          - type_id
          - genre_id
          - start_at
          - layout_id
          - company_id
          - collaboration_id
      form:
        display: 
          "Basic Details":
             - name
             - type_id
             - genre_id
             - layout_id
             - company_id
             - collaboration_id
             - description
          "Date / Time":
             - start_at
             - end_at
          "Tickets":
             - number_of_performances
             - fundraiser
             - adult_ticket_price
             - child_ticket_price
             - student_ticket_price
             - notes
          "Images":
             - images
          "Staff":
             - staff
          "Cast":
             - cast
          "Donations":
             - donations
          "Financial":
          "Notes":
             - notes
      edit:    ~
      new:     ~