generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Production
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          production
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        display:
          - =name
          - company
      filter:
        display:
          - name
          - company_id
      form:
        display:
          "Basic Details":
             - name
             - pvm_code
             - company_id
             - genres_list
             - types_list
             - description
          "Personnel":
             - director_id
             - producer_id
             - technician_id
          "Performances":
             - Performances
             - Add Performance
          "Booking":
             - booking_status
             - contract_details
             - collaboration_nature
          "Financial":
             - funding
             - gross_income
          "Notes":
             - notes
      edit:    ~
      new:     ~