generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Production
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          production
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        display:
          - =name
          - type
          - genre
          - venue
          - start_at
          - end_at
          - company
          - director
          - producer
      filter:
        display:
          - name
          - type_id
          - genre_id
          - start_at
          - layout_id
          - company_id
          - collaboration_id
      form:
        display:
          "Basic Details":
             - name
             - type_id
             - genre_id
             - layout_id
             - company_id
             - collaboration_id
             - start_at
             - end_at
             - description
          "Personnel":
             - director_id
             - producer_id
             - technician_id
          "Financial":
             - gross_income
          "Notes":
             - notes
      edit:    ~
      new:     ~