generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Staff
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          staff
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        title: Staff / Creative Team
        display:
          - name
      filter:
        display:
          - name
      form:    ~
      edit:
        title: %%name%%
      new:
        title: New Staff / Creative Team Member