generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Staff
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          staff
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        display:
          - name
          - email
          - telephone
      filter:
        display:
          - name
          - email
          - telephone
      form:    ~
      edit:    ~
      new:     ~
