generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Image
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          image
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:    ~
      filter:
        display:
          - =title
          - production_id
          - person_id
      form:    ~
      edit:    ~
      new:     ~
