Funder:
  actAs:
    Timestampable: ~
  columns:
    name:
      type: string(255)
      notnull: true
    description: string
  options:
    orderBy: name asc
  relations:
    Productions:
      class: Production
      refClass: Donation
      local: funder_id
      foreign: production_id
      foreignAlias: Funders
    Donations:
      class: Donation
      local: id
      foreign: funder_id
      type: many
      onDelete: cascade
      cascade: [delete]

Donation:
  columns:
    production_id:
      type: integer(20)
      notnull: true
    funder_id:
      type: integer(20)
      notnull: true
    amount: float
    description: string
  relations:
    Production:
      local: production_id
      foreign: id
      foreignAlias: Donations
    Funder:
      local: funder_id
      foreign: id
      foreignAlias: Donations