Image:
  actAs:
    Timestampable: ~
    Sluggable:
      unique: true
      fields: [title]
      canUpdate: true
  columns:
    title:
      type: string(255)
      notnull: true
    caption: string(255)
    production_id: integer(20)
    person_id: integer(20)
    path:
      type: string(255)
      notnull: true