Image:
  actAs:
    Timestampable: ~
    Sluggable:
      unique: true
      fields: [title]
      canUpdate: true
  columns:
    title:
      type: string(255)
      notnull: true
    path:
      type: string(255)
      notnull: true