Performer:
  inheritance:
    type: concrete
    extends: Person
  columns:
    gender:
      type: enum
      values: [Male, Female]
      notnull: true

Character:
  actAs:
    Timestampable: ~
  columns:
    name:
      type: string(255)
      notnull: true
    gender:
      type: enum
      values: [Male, Female]
      notnull: true
    performer_id:
      type: integer(20)
      notnull: true
    production_id:
      type: integer(20)
      notnull: true
    image_id: integer(20)
  options:
    orderBy: name asc
  relations:
    Performer:
      local: performer_id
      foreign: id
      foreignAlias: Characters
    Production:
      local: production_id
      foreign: id
      foreignAlias: Characters
    Image:
      local: image_id
      foreign: id