Performer:
  inheritance:
    type: concrete
    extends: Person
  columns:
    gender:
      type: enum
      values: [Male, Female]
      notnull: true
  relations:
    Characters:
      class: Character
      local: id
      foreign: performer_id
      type: many
      onDelete: cascade
      cascade: [delete]

Character:
  actAs:
    Timestampable: ~
  columns:
    name:
      type: string(255)
      notnull: true
    gender:
      type: enum
      values: [Male, Female]
      notnull: true
    performer_id:
      type: integer(20)
      notnull: true
    production_id:
      type: integer(20)
      notnull: true
  options:
    orderBy: name asc
  relations:
    Performer:
      local: performer_id
      foreign: id
      foreignAlias: Characters
    Production:
      local: production_id
      foreign: id
      foreignAlias: Characters