Person:
  actAs:
    Timestampable: ~
  columns:
    name:
      type: string(255)
      notnull: true
    image_id: integer(20)
  options:
    orderBy: name asc
  relations:
    Image:
      local: image_id
      foreign: id