Production:
  actAs:
    Timestampable: ~
  columns:
    name:
      type: string(255)
      notnull: true
    type_id: integer(20)
    genre_id: integer(20)
    layout_id: integer(20)
    company_id: integer(20)
    collaboration_id: integer(20)
    shot_image_id: integer(20)
    set_design_image_id: integer(20)
    description: string()
    start_at: timestamp
    end_at: timestamp
    number_of_performances: integer(20)
    fundraiser:
      type: boolean
      default: false
    adult_ticket_price: float
    child_ticket_price: float
    student_ticket_price: float
    notes: string()
  options:
    orderBy: start_at desc
  relations:
    Type:
      local: type_id
      foreign: id
      foreignAlias: Productions
    Genre:
      local: genre_id
      foreign: id
      foreignAlias: Productions
    Layout:
      local: layout_id
      foreign: id
      foreignAlias: Productions
    Company:
      local: company_id
      foreign: id
      foreignAlias: Productions
    Collaboration:
      local: collaboration_id
      foreign: id
      foreignAlias: Productions
    Shot:
      class: Image
      local: shot_image_id
      foreign: id
    SetDesign:
      class: Image
      local: set_design_image_id
      foreign: id
    Staff:
      refClass: ProductionStaff
      local: production_id
      foreign: staff_id
    Roles:
      class: Role
      refClass: ProductionStaff
      local: production_id
      foreign: role_id

Type:
  columns:
    name:
      type: string(255)
      notnull: true
  options:
    orderBy: name asc

Genre:
  columns:
    name:
      type: string(255)
      notnull: true
  options:
    orderBy: name asc

Company:
  actAs:
    Timestampable: ~
  columns:
    name:
      type: string(255)
      notnull: true
    email: string(255)
    telephone: string(255)
    mobile: string(255)
    address_line_1: string(255)
    address_line_2: string(255)
    address_line_3: string(255)
    address_line_4: string(255)
    post_code: string(20)
    description: string()
  options:
    orderBy: name asc

Collaboration:
  columns:
    name:
      type: string(255)
      notnull: true
    description:
      type: string()
  options:
    orderBy: name asc