Production:
  actAs:
    Timestampable: ~
  columns:
    name:
      type: string(255)
      notnull: true
    type_id: integer(20)
    genre_id: integer(20)
    layout_id: integer(20)
    company_id: integer(20)
    collaboration_id: integer(20)
    shot_image_id: integer(20)
    set_design_image_id: integer(20)
    description: string()
    start_at: timestamp
    end_at: timestamp
    number_of_performances: integer(20)
    matinee_performance_time: time
    evening_performance_time: time
    various_performance_times:
      type: boolean
      default: false
    seating:
      type: enum
      values: [Reserved, Partially Reserved, Not Reserved]
    fundraiser:
      type: boolean
      default: false
    full_ticket_min_price: float
    full_ticket_max_price: float
    concessionary_ticket_min_price: float
    concessionary_ticket_max_price: float
    notes: string()
    complete:
      type: boolean
      default: false
  options:
    orderBy: start_at desc
  relations:
    Type:
      local: type_id
      foreign: id
      foreignAlias: Productions
      onDelete: set null
    Genre:
      local: genre_id
      foreign: id
      foreignAlias: Productions
      onDelete: set null
    Layout:
      local: layout_id
      foreign: id
      foreignAlias: Productions
      onDelete: set null
    Company:
      local: company_id
      foreign: id
      foreignAlias: Productions
      onDelete: set null
    Collaboration:
      local: collaboration_id
      foreign: id
      foreignAlias: Productions
      onDelete: set null
    Shot:
      class: Image
      local: shot_image_id
      foreign: id
      onDelete: cascade
      cascade: [delete]
    SetDesign:
      class: Image
      local: set_design_image_id
      foreign: id
      onDelete: cascade
      cascade: [delete]
    Staff:
      refClass: ProductionStaff
      local: production_id
      foreign: staff_id
    Roles:
      class: Role
      refClass: ProductionStaff
      local: production_id
      foreign: role_id
    ProductionStaff:
      local: id
      foreign: production_id
      onDelete: cascade
      cascade: [delete]
    Characters:
      class: Character
      local: id
      foreign: production_id
      type: many
      onDelete: cascade
      cascade: [delete]
    Donations:
      class: Donation
      local: id
      foreign: production_id
      type: many
      onDelete: cascade
      cascade: [delete]

Type:
  columns:
    name:
      type: string(255)
      notnull: true
  options:
    orderBy: name asc

Genre:
  columns:
    name:
      type: string(255)
      notnull: true
  options:
    orderBy: name asc

Company:
  actAs:
    Timestampable: ~
  columns:
    name:
      type: string(255)
      notnull: true
    email: string(255)
    telephone: string(255)
    mobile: string(255)
    address_line_1: string(255)
    address_line_2: string(255)
    address_line_3: string(255)
    address_line_4: string(255)
    post_code: string(20)
    description: string()
  options:
    orderBy: name asc

Collaboration:
  columns:
    name:
      type: string(255)
      notnull: true
    description:
      type: string()
  options:
    orderBy: name asc