Production:
  actAs:
    Timestampable: ~
  columns:
    name:
      type: string(255)
      notnull: true
    layout_id: integer(20)
    type_id: integer(20)
    genre_id: integer(20)
    image_id: integer(20)
    company_id: integer(20)
    director_id: integer(20)
    producer_id: integer(20)
    technician_id: integer(20)
    description: string()
    booking_status: string()
    contract_details: string()
    collaboration_nature: string()
    start_at: datetime()
    end_at: datetime()
    fundraiser:
      type: boolean
      default: false
    adult_ticket_price: float
    child_ticket_price: float
    student_ticket_price: float
    funding: string()
    notes: string()
    gross_income: float
  options:
    orderBy: name asc
  relations:
    Image:
      local: image_id
      foreign: id
      foreignAlias: Productions
    Layout:
      local: layout_id
      foreign: id
      foreignAlias: Productions
    Genre:
      local: genre_id
      foreign: id
      foreignAlias: Productions
    Type:
      local: type_id
      foreign: id
      foreignAlias: Productions
    Company:
      local: company_id
      foreign: id
      foreignAlias: Productions
    Director:
      class: Person
      local: director_id
      foreign: id
      foreignAlias: Productions
    Producer:
      class: Person
      local: producer_id
      foreign: id
      foreignAlias: Productions
    Technician:
      class: Person
      local: technician_id
      foreign: id
      foreignAlias: Productions
    Sponsors:
      class: Sponsor
      refClass: ProductionSponsor
      local: production_id
      foreign: sponsor_id
      foreignAlias: Productions

Person:
  actAs:
    Timestampable: ~
  columns:
    name:
      type: string(255)
      notnull: true
    image_id: integer(20)
    email: string(255)
    telephone: string(255)
    gender:
      type: enum
      values: [Male, Female]
      notnull: true
  options:
    orderBy: name asc
  relations:
    Image:
      local: image_id
      foreign: id

Character:
  actAs:
    Timestampable: ~
  columns:
    name:
      type: string(255)
      notnull: true
    gender:
      type: enum
      values: [Male, Female]
      notnull: true
    actor_id:
      type: integer(20)
      notnull: true
    production_id:
      type: integer(20)
      notnull: true
  options:
    orderBy: name asc
  relations:
    Actor:
      class: Person
      local: actor_id
      foreign: id
      foreignAlias: Characters
    Production:
      local: production_id
      foreign: id
      foreignAlias: Characters

Type:
  columns:
    name:
      type: string(255)
      notnull: true
  options:
    orderBy: name asc

Genre:
  columns:
    name:
      type: string(255)
      notnull: true
  options:
    orderBy: name asc

ProductionSponsor:
  columns:
    production_id:
      type: integer(20)
      primary: true
    sponsor_id:
      type: integer(20)
      primary: true
  relations:
    Production:
      class: Production
      local: production_id
      foreign: id
    Sponsor:
      class: Sponsor
      local: sponsor_id
      foreign: id

Sponsor:
  actAs:
    Timestampable: ~
  columns:
    name:
      type: string(255)
      notnull: true
  options:
    orderBy: name asc
  relations:
    Productions:
      class: Production
      refClass: ProductionSponsor
      local: sponsor_id
      foreign: production_id
      foreignAlias: Sponsors

Venue:
  columns:
    name:
      type: string(255)
      notnull: true
    telephone: string(255)
  options:
    orderBy: name asc

Layout:
  columns:
    name:
      type: string(255)
      notnull: true
    venue_id:
      type: integer(20)
      notnull: true
    capacity:
      type: integer(20)
  options:
    orderBy: name asc
  relations:
    Venue:
      local: venue_id
      foreign: id
      foreignAlias: Layouts

Company:
  actAs:
    Timestampable: ~
  columns:
    name:
      type: string(255)
      notnull: true
    email: string(255)
    telephone: string(255)
    description: string()
  options:
    orderBy: name asc

Image:
  actAs:
    Timestampable: ~
    Sluggable:
      unique: true
      fields: [title]
      canUpdate: true
  columns:
    title:
      type: string(255)
      notnull: true
    caption: string(255)
    production_id: integer(20)
    person_id: integer(20)
    path:
      type: string(255)
      notnull: true