actAs:
  Timestampable: ~

Production:
  columns:
    name:
      type: string(255)
      notnull: true
    company_id:
      type: integer(20)
      notnull: true
    booking_status:
      type: string()
    collaboration_nature:
      type: string()
    general_show_information:
      type: string()
  options:
    orderBy: name asc
  relations:
    Company:
      local: company_id
      foreign: id
      foreignAlias: Productions

Performance:
  columns:
    production_id:
      type: integer(20)
      notnull: true
    venue_id:
      type: integer(20)
      notnull: true
    ticket_price:
      type: integer(20)
    ticket_price_concessionary:
      type: integer(20)
    ticket_price_notes:
      type: string()
    setup_at:
      type: timestamp()
  options:
    orderBy: setup_at asc
  relations:
    Venue:
      local: venue_id
      foreign: id
      foreignAlias: Performances

Show:
  columns:
    performance_id:
      type: integer(20)
      notnull: true
    show_at:
      type: timestamp()
      notnull: true
  options:
    orderBy: performance_at asc
  relations:
    Performance:
      local: performance_id
      foreign: id
      foreignAlias: Shows

Venue:
  columns:
    name:
      type: string(255)
      notnull: true
    capacity:
      type: integer(20)
  options:
    orderBy: name asc

Company:
  columns:
    name:
      type: string(255)
      notnull: true
  options:
    orderBy: name asc