actAs:
  Timestampable: ~

Production:
  columns:
    name:
      type: string(255)
      notnull: true
    pvm_code: string(20)
    genre_id: integer(20)
    production_type_id: integer(20)
    company_id: integer(20)
    director_id: integer(20)
    producer_id: integer(20)
    technician_id: integer(20)
    description: string()
    booking_status: string()
    contract_details: string()
    collaboration_nature: string()
    funding: string()
    notes: string()
    gross_income: integer(20)
  options:
    orderBy: name asc
  relations:
    Company:
      local: company_id
      foreign: id
      foreignAlias: Productions
    Type:
      class: ProductionType
      local: production_type_id
      foreign: id
      foreignAlias: Productions

ProductionType:
  columns:
    name:
      type: string(255)
      notnull: true
  options:
    orderBy: name asc

Performance:
  columns:
    production_id:
      type: integer(20)
      notnull: true
    venue_id:
      type: integer(20)
      notnull: true
    adult_tickets_available: integer(20)
    adult_ticket_price: integer(20)
    child_tickets_available: integer(20)
    child_ticket_price: integer(20)
    complimentary_tickets_available: integer(20)
    student_tickets_available: integer(20)
    student_ticket_price: integer(20)
    setup_at: timestamp()
  options:
    orderBy: setup_at asc
  relations:
    Venue:
      local: venue_id
      foreign: id
      foreignAlias: Performances

Show:
  columns:
    performance_id:
      type: integer(20)
      notnull: true
    show_at:
      type: timestamp()
      notnull: true
    adult_tickets_sold: integer(20)
    adult_attendees: integer(20)
    child_tickets_sold: integer(20)
    child_attendees: integer(20)
    complimentary_tickets_sold: integer(20)
    student_tickets_sold: integer(20)
    student_attendees: integer(20)
  options:
    orderBy: performance_at asc
  relations:
    Performance:
      local: performance_id
      foreign: id
      foreignAlias: Shows

Genre:
  columns:
    name:
      type: string(255)
      notnull: true
  options:
    orderBy: name asc

Venue:
  columns:
    name:
      type: string(255)
      notnull: true
    telephone: string(255)
    capacity: integer(20)
  options:
    orderBy: name asc

Company:
  columns:
    name:
      type: string(255)
      notnull: true
    email: string(255)
    telephone: string(255)
    description: string()
  options:
    orderBy: name asc