Production:
  actAs:
    Timestampable: ~
  columns:
    name:
      type: string(255)
      notnull: true
    pvm_code: string(20)
    image_id: integer(20)
    company_id: integer(20)
    director_id: integer(20)
    producer_id: integer(20)
    technician_id: integer(20)
    description: string()
    booking_status: string()
    contract_details: string()
    collaboration_nature: string()
    funding: string()
    notes: string()
    gross_income: float
  options:
    orderBy: name asc
  relations:
    Image:
      local: image_id
      foreign: id
      foreignAlias: Productions
    Genres:
      class: Genre
      refClass: ProductionGenre
      local: production_id
      foreign: genre_id
      foreignAlias: Productions
    Types:
      class: Type
      refClass: ProductionType
      local: production_id
      foreign: type_id
      foreignAlias: Productions
    Sponsors:
      class: Sponsor
      refClass: ProductionSponsor
      local: production_id
      foreign: sponsor_id
      foreignAlias: Productions
    Company:
      local: company_id
      foreign: id
      foreignAlias: Productions
    Director:
      class: Person
      local: director_id
      foreign: id
      foreignAlias: Productions
    Producer:
      class: Person
      local: producer_id
      foreign: id
      foreignAlias: Productions
    Technician:
      class: Person
      local: technician_id
      foreign: id
      foreignAlias: Productions

Performance:
  actAs:
    Timestampable: ~
  columns:
    production_id:
      type: integer(20)
      notnull: true
    venue_id:
      type: integer(20)
      notnull: true
    adult_tickets_available: integer(20)
    adult_ticket_price: float
    child_tickets_available: integer(20)
    child_ticket_price: float
    complimentary_tickets_available: integer(20)
    student_tickets_available: integer(20)
    student_ticket_price: float
    setup_at: timestamp()
  options:
    orderBy: setup_at asc
  relations:
    Production:
      local: production_id
      foreign: id
      foreignAlias: Performances
    Venue:
      local: venue_id
      foreign: id
      foreignAlias: Performances

Show:
  actAs:
    Timestampable: ~
  columns:
    performance_id:
      type: integer(20)
      notnull: true
    show_at:
      type: timestamp()
      notnull: true
    adult_tickets_sold: integer(20)
    adult_attendees: integer(20)
    child_tickets_sold: integer(20)
    child_attendees: integer(20)
    complimentary_tickets_sold: integer(20)
    student_tickets_sold: integer(20)
    student_attendees: integer(20)
  options:
    orderBy: show_at asc
  relations:
    Performance:
      local: performance_id
      foreign: id
      foreignAlias: Shows

Person:
  actAs:
    Timestampable: ~
  columns:
    name:
      type: string(255)
      notnull: true
    image_id: integer(20)
    email: string(255)
    telephone: string(255)
    gender:
      type: enum
      values: [Male, Female]
      notnull: true
  options:
    orderBy: name asc
  relations:
    Image:
      local: image_id
      foreign: id

Character:
  actAs:
    Timestampable: ~
  columns:
    name:
      type: string(255)
      notnull: true
    gender:
      type: enum
      values: [Male, Female]
      notnull: true
    actor_id:
      type: integer(20)
      notnull: true
    production_id:
      type: integer(20)
      notnull: true
  options:
    orderBy: name asc
  relations:
    Actor:
      class: Person
      local: actor_id
      foreign: id
      foreignAlias: Characters
    Production:
      local: production_id
      foreign: id
      foreignAlias: Characters

ProductionType:
  columns:
    production_id:
      type: integer(20)
      primary: true
    type_id:
      type: integer(20)
      primary: true
  relations:
    Production:
      class: Production
      local: production_id
      foreign: id
    Type:
      class: Type
      local: type_id
      foreign: id

Type:
  columns:
    name:
      type: string(255)
      notnull: true
  options:
    orderBy: name asc
  relations:
    Productions:
      class: Production
      refClass: ProductionType
      local: type_id
      foreign: production_id
      foreignAlias: Types

ProductionGenre:
  columns:
    production_id:
      type: integer(20)
      primary: true
    genre_id:
      type: integer(20)
      primary: true
  relations:
    Production:
      class: Production
      local: production_id
      foreign: id
    Genre:
      class: Genre
      local: genre_id
      foreign: id

Genre:
  columns:
    name:
      type: string(255)
      notnull: true
  options:
    orderBy: name asc
  relations:
    Productions:
      class: Production
      refClass: ProductionGenre
      local: genre_id
      foreign: production_id
      foreignAlias: Genres

ProductionSponsor:
  columns:
    production_id:
      type: integer(20)
      primary: true
    sponsor_id:
      type: integer(20)
      primary: true
  relations:
    Production:
      class: Production
      local: production_id
      foreign: id
    Sponsor:
      class: Sponsor
      local: sponsor_id
      foreign: id

Sponsor:
  actAs:
    Timestampable: ~
  columns:
    name:
      type: string(255)
      notnull: true
  options:
    orderBy: name asc
  relations:
    Productions:
      class: Production
      refClass: ProductionSponsor
      local: sponsor_id
      foreign: production_id
      foreignAlias: Sponsors

Venue:
  actAs:
    Timestampable: ~
  columns:
    name:
      type: string(255)
      notnull: true
    telephone: string(255)
    capacity: integer(20)
  options:
    orderBy: name asc

Company:
  actAs:
    Timestampable: ~
  columns:
    name:
      type: string(255)
      notnull: true
    email: string(255)
    telephone: string(255)
    description: string()
  options:
    orderBy: name asc

Image:
  actAs:
    Timestampable: ~
    Sluggable:
      unique: true
      fields: [title]
      canUpdate: true
  columns:
    title:
      type: string(255)
      notnull: true
    caption: string(255)
    production_id: integer(20)
    person_id: integer(20)
    path:
      type: string(255)
      notnull: true
  relations:
    Production:
      local: production_id
      foreign: id
      foreignAlias: Images
    Person:
      local: person_id
      foreign: id
      foreignAlias: Images