Sponsor:
  actAs:
    Timestampable: ~
  columns:
    name:
      type: string(255)
      notnull: true
    description: string
  options:
    orderBy: name asc
  relations:
    Productions:
      class: Production
      refClass: Donation
      local: sponsor_id
      foreign: production_id
      foreignAlias: Sponsors

Donation:
  columns:
    production_id:
      type: integer(20)
      notnull: true
    sponsor_id:
      type: integer(20)
      notnull: true
    amount: float
    description: string
  relations:
    Production:
      local: production_id
      foreign: id
      foreignAlias: Donations
    Sponsor:
      local: sponsor_id
      foreign: id
      foreignAlias: Donations