Staff:
  inheritance:
    type: concrete
    extends: Person
  relations:
    Productions:
      class: Production
      refClass: ProductionStaff
      local: staff_id
      foreign: production_id
    Roles:
      class: Role
      refClass: ProductionStaff
      local: staff_id
      foreign: role_id
    ProductionStaff:
      local: id
      foreign: staff_id
      type: many
      onDelete: cascade
      cascade: [delete]

ProductionStaff:
  columns:
    production_id:
      type: integer(20)
      primary: true
    role_id:
      type: integer(20)
      primary: true
    staff_id:
      type: integer(20)
      notnull: true
  relations:
    Production:
      local: production_id
      foreign: id
    Role:
      local: role_id
      foreign: id
    Staff:
      local: staff_id
      foreign: id

Department:
  columns:
    name:
      type: string(255)
      notnull: true
  relations:
    Roles:
      class: Role
      local: id
      foreign: department_id
      type: many
      onDelete: cascade
      cascade: [delete]

Role:
  columns:
    name:
      type: string(255)
      unique: true
      notnull: true
    department_id:
      type: integer(20)
      notnull: true
  relations:
    Department:
      local: department_id
      foreign: id
      foreignAlias: Roles
    Staff:
      refClass: ProductionStaff
      local: role_id
      foreign: staff_id
    ProductionStaff:
      local: id
      foreign: role_id
      type: many
      onDelete: cascade
      cascade: [delete]